name: Deploy Backend to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
            service_account_key: ${{ secrets.GCP_SA_KEY }}
            project_id: ${{ secrets.GCP_PROJECT_ID }}
    
      - name: Configure Docker authentication
        run:  gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev
     
      - name: Generate Prisma Client
        run: npx prisma generate
     
      - name: Build Docker image
        run: docker build -t ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/movienotes/backend:${{ github.sha }} .
    
      - name: Authenticate Docker to Artifact Registry
        run: gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev

      - name: Push Docker image
        run: docker push ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/movienotes/backend:${{ github.sha }}
      
      - name: Deploy to Cloud Run
        run: gcloud run deploy movienotes-backend \
            --image ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/movienotes/backend:${{ github.sha }} \
            --region ${{ secrets.GCP_REGION }} \
            --platform managed \
            --allow-unauthenticated
       
       
